resolver = 1
title = "OpenCode"
identifier = "ora-space.opencode"
namespace = "official"
kind = "agent"
version = "0.2.3"
description = "Ora Space OpenCode Agent"
homepage = "https://github.com/ora-space/opencode-agent"
license = "Apache-2.0"

url = "https://github.com/ora-space/opencode-agent/releases/download/v0.2.3/ora-space.opencode-v0.2.3.orax"
sha256 = "673242a8b46c4601639c807b9faf48a3b627870e03f82e90d399ff78093e402c"
