resolver = 1
title = "Matt Pocock Skills"
identifier = "mattpocock.skills"
namespace = "official"
kind = "skill"
version = "1.3.1"
description = "Matt Pocock's skills for real engineering"
homepage = "https://github.com/mattpocock/skills"
license = "MIT"

url = "https://github.com/ora-space/mattpocock-skill/releases/download/v1.3.1/mattpocock.skills-v1.3.1.orax"
sha256 = "c3de8a2c6863a1864901fc55e7eb42e22fe0829fb958249de59c5d4e715def64"
