resolver = 1
title = "Codex"
identifier = "ora-space.codex"
namespace = "official"
kind = "agent"
version = "0.1.0"
description = "Ora Space Codex Agent"
homepage = "https://github.com/ora-space/codex-agent"
license = "Apache-2.0"

url = "https://github.com/ora-space/codex-agent/releases/download/v0.1.0/ora-space.codex-v0.1.0.orax"
sha256 = "1a4a60b6f34587f04c8d65b56b26aab58e95830f276beebb6746c789914c6808"
