resolver = 1
title = "Codex"
identifier = "ora-space.codex"
namespace = "official"
kind = "agent"
version = "0.3.14"
description = "Ora Space Codex Agent"
homepage = "https://github.com/ora-space/codex-agent"
license = "Apache-2.0"

[[targets]]
target = "x86_64-pc-windows-msvc"
url = "https://github.com/ora-space/codex-agent/releases/download/v0.3.14/ora-space.codex-v0.3.14-x86_64-pc-windows-msvc.orax"
sha256 = "1ec90aed062f130ad29d2886ae86bcfb3742b987346d960306d672135d16fbc6"

[[targets]]
target = "aarch64-apple-darwin"
url = "https://github.com/ora-space/codex-agent/releases/download/v0.3.14/ora-space.codex-v0.3.14-aarch64-apple-darwin.orax"
sha256 = "d67c234f96aaf23fd3271201481b8a8e581f1b6e8e373c592ad4494ed5e1b362"

[[targets]]
target = "x86_64-unknown-linux-gnu"
url = "https://github.com/ora-space/codex-agent/releases/download/v0.3.14/ora-space.codex-v0.3.14-x86_64-unknown-linux-gnu.orax"
sha256 = "a32b463a1a677e932bf1eca075bf8def0aa4a5254e2c42e459e180bd601d8b03"

[[targets]]
target = "aarch64-unknown-linux-gnu"
url = "https://github.com/ora-space/codex-agent/releases/download/v0.3.14/ora-space.codex-v0.3.14-aarch64-unknown-linux-gnu.orax"
sha256 = "75384d334795204bb846db770ea6d71e2b790418ad90c0832198108922f8185f"
